package ask.helloworld.company;


public class Company 
{

	String companyName;
	
	String name = "default name";

	public static int staticTest = 0;
	
	public static final String MALE = "MALE";

	// for same pkg or extended class
	protected int protectedJ = 2;

	// default
	int k = 3; // for same pkg
	
	// only for me
	private int i = 1;
	
	
	enum Gender{
		MALE,
		FEMALE
	}
	
	
	// Constructor : 선언하면서 값 입력 받도록 함(init하기 위함)
	// if not exist, then it is generated by system during compile.
	// no return type, init for companyName(Company class) 

	// basic constructor by system or manual
	public Company()
	{
//		this.companyName = "No name";  
// or
		this("No name"); // 아래 생성자 이용
	}	
	
	
	public Company(String companyName)
	{
//		companyName = companyName; // 동일 변수인 경우 구분이 안감
		this.companyName = companyName; // this는 my field 것을 말함
	}
	
	
	public void setName(String input)
	{
		name = input;
	}
	
	
	// Method Overloading
	public void setName(char input, String name)
	{
		this.name = input + name;
	}
	
	
	public String getName()
	{
		return name;
	}
	
	public void test()
	{
		System.out.println("company test");
	}
		
	
	
}
